version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${VOTIFY_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${VOTIFY_MYSQL_DATABASE}
      - MYSQL_USER=${VOTIFY_MYSQL_USER}
      - MYSQL_PASSWORD=${VOTIFY_MYSQL_PASSWORD}
      - VOTIFY_REDIS_ADDR=redis:6379
      - VOTIFY_MINIO_ENDPOINT=minio:9000
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    env_file:
      - .env
    command: redis-server --requirepass ${VOTIFY_REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${VOTIFY_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${VOTIFY_MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    depends_on:
      - voting-service
      - minio

  voting-service:
    build: ./voting-service
    ports:
      - "${VOTIFY_SERVICE_PORT}:${VOTIFY_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      - VOTIFY_DB_HOST=mysql
      - VOTIFY_DB_PORT=3306
      - VOTIFY_REDIS_ADDR=redis:6379
      - VOTIFY_MINIO_ENDPOINT=minio:9000
    depends_on:
      - redis
      - mysql
      - minio

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "${VOTIFY_PHPMYADMIN_PORT}:80" # Changed from 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${VOTIFY_MYSQL_USER}
      - PMA_PASSWORD=${VOTIFY_MYSQL_PASSWORD}

volumes:
  mysql-data:
  redis-data:
  minio-data:
