apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-config
data:
  NOTIFY_ENVIRONMENT: "production"
  NOTIFY_SERVICE_PORT: "8080"
  NOTIFY_MYSQL_DATABASE: "voting_db"
  NOTIFY_MINIO_ENDPOINT: "minio:9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-secrets
stringData:
  NOTIFY_MYSQL_ROOT_PASSWORD: "rootpass"
  NOTIFY_MYSQL_USER: "admin"
  NOTIFY_MYSQL_PASSWORD: "adminpass"
  NOTIFY_REDIS_PASSWORD: "redispass"
  NOTIFY_MINIO_ROOT_USER: "minioadmin"
  NOTIFY_MINIO_ROOT_PASSWORD: "minioadmin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: notify-secrets
            - configMapRef:
                name: notify-config
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notify-secrets
                  key: NOTIFY_MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapRef:
                  name: notify-config
                  key: NOTIFY_MYSQL_DATABASE
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: notify-secrets
                  key: NOTIFY_MYSQL_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notify-secrets
                  key: NOTIFY_MYSQL_PASSWORD
          ports:
            - containerPort: 80
