apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
spec:
  template:
    spec:
      containers:
        - name: mc
          image: minio/mc
          command: [
              "sh",
              "-c",
              "mc alias set minio http://minio:9000 minioadmin minioadmin;
              mc mb minio/voting-images;
              mc policy set public minio/voting-images",
            ]
      restartPolicy: Never
