/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Connection status
 */
export type ChatServiceInternalModelsConnectionDataStatus = typeof ChatServiceInternalModelsConnectionDataStatus[keyof typeof ChatServiceInternalModelsConnectionDataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatServiceInternalModelsConnectionDataStatus = {
  connected: 'connected',
  disconnected: 'disconnected',
} as const;
