/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Data structure for channel.message message type
 */
export interface ChatServiceInternalModelsChannelMessageData {
  /** ID of the channel where message is sent */
  channel_id: string;
  /** Text content of the message */
  text?: string;
  /**
   * Optional URL attachment
   * @nullable
   */
  url?: string | null;
  /**
   * Optional file name for attachments
   * @nullable
   */
  fileName?: string | null;
  /**
   * Optional ID of message being replied to
   * @nullable
   */
  reply_to_id?: string | null;
}
