/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsWebSocketMessageTypeProperty } from './chatServiceInternalModelsWebSocketMessageTypeProperty';

/**
 * Base WebSocket message structure that all messages follow
 */
export interface ChatServiceInternalModelsWebSocketMessage {
  /** Unique message identifier */
  id: string;
  /** Message type enum - see WebSocketMessageType for valid values */
  type: ChatServiceInternalModelsWebSocketMessageTypeProperty;
  /** Message payload data - structure depends on message type */
  data: unknown;
  /** Unix timestamp when message was created */
  timestamp: number;
  /** ID of the user who sent the message */
  user_id?: string;
}
