/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsWebSocketMessage } from './chatServiceInternalModelsWebSocketMessage';

/**
 * Example WebSocket messages for different message types
 */
export interface ChatServiceInternalModelsWebSocketExampleMessages {
  /** Example channel join message */
  channel_join_example?: ChatServiceInternalModelsWebSocketMessage;
  /** Example channel message */
  channel_message_example?: ChatServiceInternalModelsWebSocketMessage;
  /** Example error message */
  error_example?: ChatServiceInternalModelsWebSocketMessage;
  /** Example typing indicator */
  typing_indicator_example?: ChatServiceInternalModelsWebSocketMessage;
}
