/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Data structure for channel.member.join and channel.member.leave message types
 */
export interface ChatServiceInternalModelsMemberJoinLeaveData {
  /** ID of the channel */
  channel_id: string;
  /** ID of the user joining/leaving */
  user_id: string;
  /** Username of the user joining/leaving */
  username?: string;
}
