/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Message type enum - see WebSocketMessageType for valid values
 */
export type ChatServiceInternalModelsWebSocketMessageTypeProperty = typeof ChatServiceInternalModelsWebSocketMessageTypeProperty[keyof typeof ChatServiceInternalModelsWebSocketMessageTypeProperty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatServiceInternalModelsWebSocketMessageTypeProperty = {
  connectionconnect: 'connection.connect',
  connectiondisconnect: 'connection.disconnect',
  connectionping: 'connection.ping',
  connectionpong: 'connection.pong',
  channeljoin: 'channel.join',
  channelleave: 'channel.leave',
  channelmessage: 'channel.message',
  channeltyping: 'channel.typing',
  channelstop_typing: 'channel.stop_typing',
  channelmemberjoin: 'channel.member.join',
  channelmemberleave: 'channel.member.leave',
  userstatus: 'user.status',
  usernotification: 'user.notification',
  error: 'error',
} as const;
