/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the user
 */
export type ChatServiceInternalModelsUserStatusDataStatus = typeof ChatServiceInternalModelsUserStatusDataStatus[keyof typeof ChatServiceInternalModelsUserStatusDataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatServiceInternalModelsUserStatusDataStatus = {
  online: 'online',
  offline: 'offline',
  away: 'away',
  busy: 'busy',
} as const;
