/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsConnectionDataStatus } from './chatServiceInternalModelsConnectionDataStatus';

/**
 * Data structure for connection.connect and connection.disconnect message types
 */
export interface ChatServiceInternalModelsConnectionData {
  /** Client connection ID */
  client_id?: string;
  /** Connection status */
  status?: ChatServiceInternalModelsConnectionDataStatus;
}
