/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Data structure for connection.ping and connection.pong message types
 */
export interface ChatServiceInternalModelsPingPongData {
  /** Timestamp for ping/pong */
  timestamp?: number;
  /**
   * Optional ping ID for pong responses
   * @nullable
   */
  ping_id?: string | null;
}
