/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsUserStatusDataStatus } from './chatServiceInternalModelsUserStatusDataStatus';

/**
 * Data structure for user.status message type
 */
export interface ChatServiceInternalModelsUserStatusData {
  /** Current status of the user */
  status: ChatServiceInternalModelsUserStatusDataStatus;
  /** Unix timestamp of last seen time */
  last_seen?: number;
}
