/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Enum of valid WebSocket message types
 */
export interface ChatServiceInternalModelsWebSocketMessageType {
  /** Channel events */
  'channel.join'?: string;
  'channel.leave'?: string;
  /** Channel member events */
  'channel.member.join'?: string;
  'channel.member.leave'?: string;
  'channel.message'?: string;
  'channel.stop_typing'?: string;
  'channel.typing'?: string;
  /** Connection events */
  'connection.connect'?: string;
  'connection.disconnect'?: string;
  'connection.ping'?: string;
  'connection.pong'?: string;
  /** Error events */
  error?: string;
  'user.notification'?: string;
  /** User events */
  'user.status'?: string;
}
