/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Data structure for error message type
 */
export interface ChatServiceInternalModelsErrorData {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /**
   * Optional additional error details
   * @nullable
   */
  details?: string | null;
}
