/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

/**
 * Data structure for channel.typing and channel.stop_typing message types
 */
export interface ChatServiceInternalModelsTypingIndicatorData {
  /** ID of the channel where typing is happening */
  channel_id: string;
  /** Whether user is currently typing */
  is_typing?: boolean;
}
